# Generated by Django 5.2.5 on 2025-09-03 05:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría', null=True)),
                ('ubicacion_pasillo', models.CharField(blank=True, help_text='Pasillo donde se encuentra la categoría', max_length=50)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la categoría está activa')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=100)),
                ('cedula', models.CharField(help_text='Cédula o identificador único del cliente', max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de teléfono del cliente', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico del cliente', max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(help_text='Nombre de la empresa proveedora', max_length=200)),
                ('contacto_nombre', models.CharField(blank=True, help_text='Nombre del contacto principal', max_length=100)),
                ('telefono', models.CharField(help_text='Número de teléfono del proveedor', max_length=15)),
                ('email', models.EmailField(help_text='Correo electrónico del proveedor', max_length=254, unique=True)),
                ('direccion', models.TextField(blank=True, help_text='Dirección física del proveedor', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del producto', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto', null=True)),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta del producto', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad en inventario')),
                ('codigo_barra', models.CharField(help_text='Código de barras del producto', max_length=100, unique=True)),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece el producto', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la venta')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total de la venta', max_digits=12)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente que realizó la compra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.cliente')),
                ('vendedor', models.ForeignKey(help_text='Empleado que realizó la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de unidades vendidas')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de la venta', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal (cantidad * precio_unitario)', max_digits=12)),
                ('producto', models.ForeignKey(help_text='Producto vendido', on_delete=django.db.models.deletion.PROTECT, to='api.producto')),
                ('venta', models.ForeignKey(help_text='Venta a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.venta')),
            ],
        ),
    ]
