# Generated by Django 5.2.5 on 2025-09-03 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proveedor'),
        ),
    ]
